config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :customers #, only: [:index, :new]

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :description, presence: true, uniqueness: { case_sensitive: false }
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :name, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :description, presence: true
  validates :price, presence: true
  validates :category, presence: true

  def full_description
    "#{self.description} - #{self.price}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_member!, except: [:index]  
  before_action :set_customer, only: [:edit, :update, :show, :destroy]

  def index
    @customers = Customer.all
  end
  
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to customers_path, notice:"Cliente cadastrado com sucesso!"
    else
      render :new
    end
  end

  def show 
    # @customer = Customer.find(params[:id])
  end

  def edit
    # @customer = Customer.find(params[:id])
  end

  def update
    # @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer.id), notice: 'Cliente atualizado com sucesso!'
    else
      render (:edit)
    end
  end

  def destroy
    if @customer.destroy
      redirect_to customers_path, notice: 'Cliente excluído com sucesso!'
    else
      render :index
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit( :id,:name,:email,:phone,:avatar,:smoker, :gender)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |f| %>
<%#= form_with url: customers_path, method: :post do |f| # URL mode: works without a model object, generating a form that still posts to customers_path%>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "erro") %> proibiu este cliente de ser salvo:</h2>
      <ul>
        <% customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email, "Email" %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :phone, "Telefone" %>
    <%= f.text_field :phone %>
  </div>

  <div>
    <%= f.label :smoker, "Fumante?" %><br>
    <%= f.radio_button :smoker, 'S', id: 'smoker_s' %>
    <%= f.label :smoker_s, 'Sim' %>

    <%= f.radio_button :smoker, 'N', id: 'smoker_n' %>
    <%= f.label :smoker_n, 'Não' %>
  </div>

  <div>
    <%= f.label :gender, "Gênero" %>
    <%= f.select :gender, [["Masculino", "male"], ["Feminino", "female"], ["Outro", "other"]] %>
  </div>

  <div>
    <%= f.label :avatar, "Foto do Perfil" %>
    <%= f.file_field :avatar %>
  </div>

  <div>
    <%= f.submit @customer.new_record? ? 'Criar Cliente' : 'Atualizar Cliente' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editando Cliente</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Voltar', customers_path %>

app/views/customers/index.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>
<h1>Listando Clientes</h1>
<table>
    <thead>
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        <% @customers.each do |customer| %>
        <tr>
            <td><%= customer.name%></td>
            <td><%= link_to "Mostrar", customer_path(customer.id) %></td>
            <td><%= link_to "Editar", edit_customer_path(customer.id) %></td>
            <td><%= link_to "Excluir", customer,data: { turbo_method: :delete, turbo_confirm: "Deseja realmente excluir?" }, id: "delete_customer_#{customer.id}" %> </td>
        </tr>
        <% end %>
    </tbody>
</table>
<%= link_to 'Novo Cliente', new_customer_path %>

app/views/customers/new.html.erb
<h1>Novo Cliente</h1>

<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice]  %></p>
<% end %>

<h1>Mostrando Cliente</h1>
<p>
    <strong>Nome</strong>
        <%= @customer.name %>    
</p>

<p>
    <strong>Email</strong>
        <%= @customer.email %>    
</p>

<p>
    <strong>Telefone</strong>
        <%= @customer.phone %>    
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tdd App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Seja Bem-vindo!</h1>
<ul>
    <li><%=link_to "Cadastro de Clientes", customers_path %></li>
</ul>